version: '3.9'
services:
  service-1: 
   container_name: ibregistry
   build: .
   image: tomcat
   ports:
   - "8094:8080"
   volumes:                                                        
        - ./sample.war:/usr/local/tomcat/webapps/sample.war
   networks:
        - demo-network 
  service-2:
   container_name: ibsso
   image: tomcat
   ports:
   - "8095:8080"
   volumes:
       - ./Hello.war:/usr/local/tomcat/webapps/Hello.war
   networks:
        - demo-network 
networks:
  demo-network:
     driver: bridge